/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;
import LinkedList.Node;
import java.util.Objects;

public class LinkedList {
    Node head;
    Node tail;
    private  int size = 0;

    public int size(){
        return size;
    }


    // insert new node at the start of linked list
    public void insert(int data) {
        Node node = new Node(data);
        if (size == 0) {
            head = node;
        } else {
            Node current = head;
            while (current.getNext() != null) {
                current = current.getNext();
            }
            current.setNext(node);
        }
        size++;
    }
    // check for a node value if exists
    public boolean includes(int data) {
        if (size != 0) {
            Node current = head;
            while (current != null) {
                if (Objects.equals(current.getData(),data)) {
                    return true;
                }
                current = current.getNext();
            }
        }
        return false;
    }

    // convert linked list node values to string
    public String listString(){
        String message = " { ";
        if (head == null){
            return "There is no data in the List";
        }else{
            Node current = head;
            message +=current.getData()+" } -> ";
            while (current.getNext() != null){
                current = current.getNext();
                message += "{ "+ (current.getData())+" } -> ";
            }
            message += "NULL";
        }
        return message;
    }


}