/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    public void maxValueTestempty() {
        BinarySearchTree binarySearchTree = new BinarySearchTree();

        assertEquals(IllegalArgumentException.class,binarySearchTree.findMaxvalue());

    }

    @Test
    public void maxValueTest(){
        BinarySearchTree binarySearchTree = new BinarySearchTree();


    }

}
