/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {

    public static void main(String[] args) {


        Graph graph = new Graph();

        graph.addVertex("Rahaf");
        graph.addVertex("Roaa");
        graph.addVertex("Ola");
        graph.addVertex("Abdalla");

        graph.addEdge("Rahaf","Roaa");
        graph.addEdge("Rahaf", "Ola");
        graph.addEdge("Rahaf", "Abdalla");
        graph.addEdge("Roaa","Ola");
        graph.addEdge("Ola","Abdalla");
        graph.addEdge("Abdalla", "Roaa");

        System.out.println(graph.printGraph());

        graph.removeEdge("Abdalla", "Ola");
        System.out.println();
        System.out.println("delete edge --> "+graph.printGraph());

        graph.removeVertex("Rahaf");
        System.out.println();
        System.out.println("delete vertex --> " + graph.printGraph());

        System.out.println();
        System.out.println(graph.getVertices());

        System.out.println();
        System.out.println(graph.getNeighbors("Roaa"));

        System.out.println();
        System.out.println(graph.breadthTraverse(graph, "Abdalla"));

        System.out.println();
        System.out.println(graph.depthFirstTraverse(graph, "Abdalla"));

        System.out.println();
        System.out.println(graph.size());

    }
}