/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {

    public static void main(String[] args) {

        // Code challenge 35
        Graph graph = new Graph();

        graph.addVertex("Rahaf");
        graph.addVertex("Roaa");
        graph.addVertex("Ola");
        graph.addVertex("Abdalla");

        graph.addEdge("Rahaf","Roaa");
        graph.addEdge("Rahaf", "Ola");
        graph.addEdge("Rahaf", "Abdalla");
        graph.addEdge("Roaa","Ola");
        graph.addEdge("Ola","Abdalla");
        graph.addEdge("Abdalla", "Roaa");

        System.out.println(graph.printGraph());

        graph.removeEdge("Abdalla", "Ola");
        System.out.println();
        System.out.println("delete edge --> "+graph.printGraph());

        graph.removeVertex("Rahaf");
        System.out.println();
        System.out.println("delete vertex --> " + graph.printGraph());

        System.out.println();
        System.out.println(graph.getVertices());

        System.out.println();
        System.out.println(graph.getNeighbors("Roaa"));

        System.out.println();
        System.out.println(graph.breadthTraverse(graph, "Abdalla"));

        System.out.println();
        System.out.println(graph.depthFirstTraverse(graph, "Abdalla"));

        System.out.println();
        System.out.println(graph.size());

        // Code challenge 36
        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        graph1.addVertex("Arendelle");
        graph1.addVertex("Metroville");
        graph1.addVertex("Monstroplolis");
        graph1.addVertex("Narnia");
        graph1.addVertex("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");


        System.out.println(graph1.breadthTraverse( "Pandora"));


    }
}