/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarySearch;

public class App {
    public static void main(String[] args) {
        int[] arr = {4, 8, 15, 16, 23, 42};
        int[] arr2 = {-131, -82, 0, 27, 42, 68, 179};
        int[] arr3 = {11, 22, 33, 44, 55, 66, 77};
        int[] arr4 = {1, 2, 3, 5, 6, 7};

        int length = arrLength(arr);
        System.out.println(BinarySearch(arr,15));
        System.out.println(BinarySearch(arr2,42));
        System.out.println(BinarySearch(arr3,90));
        System.out.println(BinarySearch(arr4,4));

    }

    public static int arrLength(int[] arr){
        int search_key = 0;
        for (int el : arr) {
            search_key = search_key +1;
        }
        return search_key;
    }

    public static int BinarySearch(int[] arr,int value){
        int arrayLength = arrLength(arr);
        int high_index = arrayLength - 1;
        int low_index = 0;

        while(low_index <= high_index){
            int mid_index = ((low_index + high_index) / 2);
            if(arr[mid_index] > value){
                high_index = mid_index - 1;
            } else if(arr[mid_index] < value){
                low_index = mid_index + 1;
            }else{
                return mid_index;
            }

        }
        return  -1;
    }
}