/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import hashtable.binarytree.BinaryTree;
import hashtable.binarytree.Node;
import org.junit.jupiter.api.Test;

import static hashtable.App.leftJoin;
import static org.junit.jupiter.api.Assertions.*;


import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;

import java.util.HashMap;

class AppTest {
    HashTable<Integer, String> hashTable;

    @DisplayName("initial setup")
    @BeforeEach
    void setUp() {
        hashTable = new HashTable<>();
        hashTable.add(7, "rahaf");
        hashTable.add(5, "roaa");
        hashTable.add(3, "ola");
    }

    @Test
    void isEmpty() {
        HashTable<Integer, String> hashTable2 = new HashTable<>();
        assertTrue(hashTable2.isEmpty());
        assertFalse(hashTable.isEmpty());
    }

    @Test
    void getSize() {
        assertEquals(3, hashTable.getSize());
    }

    @Test
    void contains() {
        assertTrue(hashTable.contains(7));
        assertFalse(hashTable.contains(9));
    }

    @Test
    void remove() {
        hashTable.remove(5);
        assertFalse(hashTable.contains(5));
        assertEquals(2, hashTable.getSize());
    }

    @Test
    void get() {
        assertEquals("roaa", hashTable.get(5));
    }

    @Test
    public void repeatedWordTest(){

        HashTable<String, Integer> test = new HashTable<String, Integer>();

        String paragraph1 = "Once upon a time, there was a brave princess who...";
        assertEquals("a", test.repeatedWord(paragraph1));

        String paragraph2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only";
        assertEquals("it", test.repeatedWord(paragraph2));

        String paragraph3= "It was a queer,  sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York";
        assertEquals("summer", test.repeatedWord(paragraph3));

    }
    @Test
    public  void repeatedWordTestNoRepeat(){

        HashTable<String, Integer> test = new HashTable<String, Integer>();

        String paragraph = "Once upon a time";
        assertEquals("no repeated words", test.repeatedWord(paragraph));
    }

    @Test
    public void intersectionTreeTest(){

        HashTable<Integer,Integer> trees = new HashTable<Integer, Integer>();
        BinaryTree tree1 = new BinaryTree();
        BinaryTree tree2 = new BinaryTree();

        tree1.setRoot(new Node(150));
        tree1.getRoot().setLeft(new Node(100));
        tree1.getRoot().setRight(new Node(250));
        tree1.getRoot().getRight().setLeft(new Node(200));
        tree1.getRoot().getRight().setRight(new Node(350));

        tree2.setRoot(new Node(42));
        tree2.getRoot().setLeft(new Node(100));
        tree2.getRoot().setRight(new Node(600));
        tree2.getRoot().getRight().setLeft(new Node(200));
        tree2.getRoot().getRight().setRight(new Node(350));

        assertEquals("[100, 200, 350]", trees.treeIntersection(tree1,tree2).toString());

    }

    @Test
    public void intersectionTreeTestNoResults(){

        HashTable<Integer,Integer> trees = new HashTable<Integer, Integer>();
        BinaryTree tree1 = new BinaryTree();
        BinaryTree tree2 = new BinaryTree();

        tree1.setRoot(new Node(150));
        tree1.getRoot().setLeft(new Node(100));
        tree1.getRoot().setRight(new Node(250));
        tree1.getRoot().getRight().setLeft(new Node(200));
        tree1.getRoot().getRight().setRight(new Node(350));

        tree2.setRoot(new Node(42));
        tree2.getRoot().setLeft(new Node(101));
        tree2.getRoot().setRight(new Node(600));
        tree2.getRoot().getRight().setLeft(new Node(201));
        tree2.getRoot().getRight().setRight(new Node(310));

        assertEquals("[]", trees.treeIntersection(tree1,tree2).toString());

    }

    @Test
    public void intersectionTreeDifferentNumOfNodes(){

        HashTable<Integer,Integer> trees = new HashTable<Integer, Integer>();
        BinaryTree tree1 = new BinaryTree();
        BinaryTree tree2 = new BinaryTree();

        tree1.setRoot(new Node(150));
        tree1.getRoot().setLeft(new Node(100));
        tree1.getRoot().setRight(new Node(250));
        tree1.getRoot().getRight().setLeft(new Node(200));
        tree1.getRoot().getRight().setRight(new Node(350));

        tree2.setRoot(new Node(42));
        tree2.getRoot().setLeft(new Node(100));
        tree2.getRoot().setRight(new Node(600));
        tree2.getRoot().getRight().setLeft(new Node(200));

        assertEquals("[100, 200]", trees.treeIntersection(tree1,tree2).toString());

    }
    @Test
    public void testLeftWithAllJoins(){
        HashMap h1 = new HashMap();
        h1.put("fond", "enamored");
        h1.put("wrath", "anger");
        h1.put("flow", "jam");

        HashMap h2 = new HashMap();
        h2.put("fond", "averse");
        h2.put("wrath", "delight");
        h2.put("flow", "test");

        assertEquals("[wrath: [ anger, delight ], flow: [ jam, test ], fond: [ enamored, averse ]]", leftJoin(h1, h2).toString());
    }

    @Test
    public void testLeftWithSomeJoins(){
        HashMap h1 = new HashMap();
        h1.put("fond", "enamored");
        h1.put("wrath", "anger");
        h1.put("diligent", "employed");
        h1.put("outfit", "garb");
        h1.put("guide", "usher");

        HashMap h2 = new HashMap();
        h2.put("fond", "averse");
        h2.put("wrath", "delight");
        h2.put("flow", "jam");


        assertEquals("[diligent: [ employed, null ], outfit: [ garb, null ], wrath: [ anger, delight ], guide: [ usher, null ], fond: [ enamored, averse ]]",leftJoin(h1, h2).toString());
    }

    @Test
    public void testLeftWithEmptySecondHashMap(){
        HashMap h1 = new HashMap();
        h1.put("fond", "enamored");
        h1.put("wrath", "anger");
        h1.put("diligent", "employed");
        h1.put("outfit", "garb");
        h1.put("guide", "usher");

        HashMap h2 = new HashMap();

        assertEquals("[diligent: [ employed, null ], outfit: [ garb, null ], wrath: [ anger, null ], guide: [ usher, null ], fond: [ enamored, null ]]", leftJoin(h1, h2).toString());

    }

    @Test
    public void testLeftBothEmptyHashMap(){
        HashMap h1 = new HashMap();
        HashMap h2 = new HashMap();

        assertEquals("[]", leftJoin(h1, h2).toString());

    }
}