/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;

class AppTest {
    HashTable<Integer, String> hashTable;

    @DisplayName("initial setup")
    @BeforeEach
    void setUp() {
        hashTable = new HashTable<>();
        hashTable.add(7, "rahaf");
        hashTable.add(5, "roaa");
        hashTable.add(3, "ola");
    }

    @Test
    void isEmpty() {
        HashTable<Integer, String> hashTable2 = new HashTable<>();
        assertTrue(hashTable2.isEmpty());
        assertFalse(hashTable.isEmpty());
    }

    @Test
    void getSize() {
        assertEquals(3, hashTable.getSize());
    }

    @Test
    void contains() {
        assertTrue(hashTable.contains(7));
        assertFalse(hashTable.contains(9));
    }

    @Test
    void remove() {
        hashTable.remove(5);
        assertFalse(hashTable.contains(5));
        assertEquals(2, hashTable.getSize());
    }

    @Test
    void get() {
        assertEquals("roaa", hashTable.get(5));
    }
}