/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    @DisplayName("selectionSortTest")
    public void selectionSortTest(){

        int[] arr1 = {8, 4, 23, 42, 16, 15};

        InsertionSort selectionSort = new InsertionSort();
        selectionSort.selectionSort(arr1);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(arr1));
    }

    @Test
    @DisplayName("reverseSortedTest")
    public void reverseSortedTest(){

        int [] arr2 ={20, 18, 12, 8, 5, -2};
        InsertionSort selectionSort = new InsertionSort();
        selectionSort.selectionSort(arr2);
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(arr2));

    }

    @Test
    @DisplayName("fewUniquesTest")
    public void fewUniquesTest(){
        int [] arr3 = {5, 12, 7, 5, 5, 7};
        InsertionSort selectionSort = new InsertionSort();
        selectionSort.selectionSort(arr3);
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(arr3));

    }

    @Test
    @DisplayName("nearlySortedTest")
    public void nearlySortedTest(){
        int [] arr4 = {2, 3, 5, 7, 13, 11};
        InsertionSort selectionSort = new InsertionSort();
        selectionSort.selectionSort(arr4);
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(arr4));

    }
}
