/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StackAndQueue;

import Animals.Cats;
import Animals.Dogs;
import Animals.AllAnimals;
import Game.DuckDuckGooseGame;
import StackQueueBraclets.BracketValidation;

public class App {
    public static void main(String[] args) throws Exception {

        System.out.println("Hello");

        Stack stack = new Stack();
        stack.push("R");
        stack.push("A");
        stack.push("H");
        stack.push("A");
        stack.push("F");

        System.out.println(stack);
        System.out.println("top element of Stack :" +stack.peek());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());

        Queue queue = new Queue();
        queue.enqueue("A");
        queue.enqueue("B");
        queue.enqueue("C");
        queue.enqueue("D");
        queue.enqueue("E");
        System.out.println(queue);
        System.out.println("top element of Queue :" + queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());


        PseudoQueue MultiStack = new PseudoQueue();
        System.out.println("enqueue => " + MultiStack.enqueue("H"));
        System.out.println("enqueue => " + MultiStack.enqueue("E"));
        System.out.println("enqueue => " + MultiStack.enqueue("L"));
        System.out.println("enqueue => " + MultiStack.enqueue("L"));
        System.out.println("enqueue => " + MultiStack.enqueue("O"));

        System.out.println("*************************************************");

        System.out.println("dequeue => " + MultiStack.dequeue());
        System.out.println("dequeue => " + MultiStack.dequeue());
        System.out.println("dequeue => " + MultiStack.dequeue());
        System.out.println("dequeue => " + MultiStack.dequeue());
        System.out.println("dequeue => " + MultiStack.dequeue());

        AnimalShelter animalShelter = new AnimalShelter();
        animalShelter.enqueue(new Animal("cats"));
        animalShelter.enqueue(new Animal("dogs"));

        animalShelter.enqueue(new Animal("cats"));

        System.out.println(animalShelter.dequeue("cats"));
        System.out.println(animalShelter.dequeue("cats"));
        System.out.println(animalShelter.dequeue("cats"));
        System.out.println(animalShelter.dequeue("dogs"));
        System.out.println(animalShelter.dequeue("dogs"));



    }


}
