/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StackAndQueue;

public class Library {
    public static void main(String[] args) {

        LinkedList List = new LinkedList<>();

        List.append(6);
        List.append(5);
        List.insert(4);
        List.insert(8);
        List.insertAfter(5,7);

        LinkedList List2 = new LinkedList<>();

        List2.append(62);
        List2.append(52);
        List2.insert(42);
        List2.insert(82);

        List.valuesToString();
        System.out.println("");
        List2.valuesToString();
        System.out.println("");

        LinkedList List3 = new LinkedList<>();
        List3.zipLists(List,List2).valuesToString();

    }
}
