/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import java.util.Arrays;
import sort.InsertionSort;

public class Library {

    public static void main(String[] args) {

        int[] arr = {8, 4, 23, 42, 16, 15};

        InsertionSort sort = new InsertionSort();
        sort.selectionSort(arr);

        System.out.println(Arrays.toString(arr));

    }
}
