/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        HashTable<Integer,String> hashTable = new HashTable<>();

        System.out.println(hashTable.getSize());
        System.out.println(hashTable.isEmpty());

        hashTable.add(7,"rahaf");
        hashTable.add(5,"roaa");
        hashTable.add(3,"ola");

        System.out.println(hashTable.isEmpty());

        System.out.println(hashTable.getSize());

        System.out.println(hashTable.get(5));

        System.out.println(hashTable.contains(7));
        System.out.println(hashTable.contains(9));
    }
}
